regions:
  # add `global` here to include IAM entities to be nuked
  - us-east-1 # will be overridden during run time based on region parameter

account-blocklist:
  - 841423564411 # Main
  - 059516066038 # Control
  - 001641974168 # Audit
  - 863906266668 # Log
  - 730335579029 # demo

# optional: restrict nuking to these resources
resource-types:
  excludes: # exclude this as will be already handled when you include S3Bucket/DynamoDBTable. Else takes a lot of time and logs get filled up
  - S3Object
  - DynamoDBTableItem
  - IAMRole
  - IAMPolicy
  # targets:
  # - IAMUser
  # - IAMUserPolicyAttachment
  # - IAMUserAccessKey
  # - S3Bucket
  # - SNSTopic
  # - SQSQueue
  # - CloudTrailTrail

accounts:
  ACCOUNT: # will be overridden during run time based on account param
    filters:
      IAMRole:
      - "ProdRoles"
      - "DoNotDeleteRoles"
      - type: regex
        value: ".*"
      IAMUser:
      - "admin"
      - type: regex
        value: ".*"
      IAMUserPolicyAttachment:
      - property: RoleName
        value: "admin"
      IAMUserAccessKey:
      - property: UserName
        value: "admin"
      S3Bucket:
      - "s3://my-bucket"
      CloudTrailTrail: # filter all CloudTrail
      - type: regex
        value: ".*"
      SNSTopic: # SNS is protected based on global exception tags inside the nuke_config_update.py
      - type: regex
        value: ".*"
      SQSQueue: [] # delete all SQS
      EC2VPC:
      - property: IsDefault
        value: "true"
      CloudFormationStack:
      - type: regex
        value: "^StackSet-scaleops-admin-access-stackset.*"
      - type: regex
        value: "^StackSet-AWS-NUKE.*"
