regions:
  # add `global` here to include IAM entities to be nuked
  - us-east-1 # will be overridden during run time based on region parameter

account-blocklist:
  - 841423564411 # Main
  - 059516066038 # Control
  - 001641974168 # Audit
  - 863906266668 # Log
  - 730335579029 # demo

# optional: restrict nuking to these resources
resource-types:
  excludes: # exclude this as will be already handled when you include S3Bucket/DynamoDBTable. Else takes a lot of time and logs get filled up
  - S3Object
  - DynamoDBTableItem
  - IAMRole
  - IAMPolicy
  # targets:
  # - IAMUser
  # - IAMUserPolicyAttachment
  # - IAMUserAccessKey
  # - S3Bucket
  # - SNSTopic
  # - SQSQueue
  # - CloudTrailTrail

accounts:
  ACCOUNT: # will be overridden during run time based on account param
    filters:
      CloudFormationStack:
      - type: regex
        value: "^StackSet-scaleops-admin-access-stackset.*"
      - type: regex
        value: "^StackSet-AWS-NUKE.*"
      EC2VPC:
      - property: IsDefault
        value: "true"
      EC2Subnet:
      - property: DefaultVPC
        value: "true"
      EC2RouteTable:
      - property: DefaultVPC
        value: "true"
      EC2DHCPOption:
      - property: DefaultVPC
        value: "true"
      EC2InternetGateway:
      - property: DefaultVPC
        value: "true"
      EC2InternetGatewayAttachment:
      - property: DefaultVPC
        value: "true"
      EC2DefaultSecurityGroupRule:
      - type: regex
        value: ".*"

